# POST /set - Define um valor na chave "chave1"
POST http://localhost:3002/api/items
Content-Type: application/json

 {
   "chave": "funcionou",
   "valor": "valor222222"
 }
# GET /get - Obtém o valor da chave "chave1"
###

GET http://localhost:3002/api/items
###
POST http://localhost:3002/api/items
Content-Type: application/json

{
  "chave": "1",
  "valor": "Item 1"
}

