# POST /set - Define um valor na chave "chave1"
POST http://localhost:3002/api/items
Content-Type: application/json

 {
   "chave": "ppp",
   "valor": "dsds",
   "cod": "222"
 }
###

PUT http://localhost:3002/api/items
Content-Type: application/json

 {
   "chave": "opa",
   "valor": "valor222222",
   "cod": "222"
 }
###

GET http://localhost:3002/api/items/Pessoas/p

###
GET http://localhost:3002/api/items/Pessoas

###
PUT http://localhost:3002/api/items/Pessoas/dusty
Content-Type: application/json

{
  "fullname": "dusty3:)",
  "adress": "Rua do areia",
  "aniversario": "10-8-87",
  "numero": "sourse 3"
}

